version: "3.7"

services:
  postgres:
    image: postgres:13.7-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - test.env

  backend:
    build: .
    command: sh /code/start.sh
    volumes:
      - .:/code
      - drones-static:/code/static
      - drones-media:/code/media
    ports:
      - "8000:8000"
    env_file:
      - test.env

    depends_on:
      - postgres

  celery-worker:
    build: .
    command: celery -A drones worker -l info
    env_file:
      - test.env
    depends_on:
      - celery-beat
      - postgres

  celery-beat:
    build: .
    command: celery -A drones beat
    env_file:
      - test.env

    depends_on:
      - redis

  redis:
    image: redis:7.0.4-alpine
    volumes:
      - redis-data:/data

volumes:
  pg-data:
  drones-static:
  drones-media:
  redis-data:
