# Generated by Django 4.0.6 on 2022-07-22 04:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadedMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered', models.BooleanField(default=False)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_loaded', to='core.drone')),
                ('medications', models.ManyToManyField(related_name='medication_loaded', to='core.medication')),
            ],
            options={
                'verbose_name': 'Loaded Medication',
                'verbose_name_plural': 'Loaded Medications',
            },
        ),
        migrations.DeleteModel(
            name='MedicationCharged',
        ),
    ]
