# Generated by Django 4.0.6 on 2022-07-22 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_loadedmedication_delete_medicationcharged'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dronelog',
            old_name='battery_history',
            new_name='history',
        ),
    ]
