# Generated by Django 4.0.6 on 2022-07-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_battery_history_dronelog_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='image',
            field=models.ImageField(blank=True, upload_to='medication/'),
        ),
    ]
